# Render.com configuration file for TailorTalk Booking Agent
# This allows single-click deployment from GitHub

services:
  # Backend API Service
  - type: web
    name: tailortalk-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CALENDAR_CREDENTIALS_PATH
        value: credentials/service-account-key.json
      - key: GOOGLE_CALENDAR_ID
        value: imdeathgate@gmail.com
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: API_HOST
        value: 0.0.0.0
      - key: DEBUG
        value: "False"
      - key: TIMEZONE
        value: UTC
      - key: PYTHONPATH
        value: /opt/render/project/src

  # Frontend Web App Service  
  - type: web
    name: tailortalk-frontend
    env: python
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: API_BASE_URL
        value: https://tailortalk-backend.onrender.com/api/v1
      - key: STREAMLIT_PORT
        value: "8501"
